name: Hello world 
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello step
        run: |
          echo " This is line 1"
          echo " This is line 2 "
 
