name: Hello World
on: workflow_dispatch
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - name: Build step
      run: echo "you are building it"
 test:
   runs-on: ubuntu-latest
   needs: build
   steps:
    - name: Test Phase 
      run: echo  "This will execute the tests"
 deploy:
   runs-on: ubuntu-latest
   needs: test
   steps:
    - name: deploy the app
      run: echo "This would deploy"
      
