name: Hello World
on: 
 push:
  branches:
   - main
   - develop
   - 'release/**'
 pull_request:
   branches:
   - main
 
jobs:
 build:
   runs-on: ubuntu-latest
   steps:
    - name: Build step
      run: echo "you are building it"

    - name: variable name
      run: echo "the variable name is:" ${{vars.MY_NAME}}

    - name: variable name
      run: echo "the secret name is:" ${{secrets.MY_SECRET}}   

     
